### PR TITLE
#93 - Use a stream if specified in createFromFile & createFromFileInGroup

### PR DESCRIPTION
**Pull request by jimmythompson**
This PR changes requestWithFileFun to allow you to take either a [WebAPI File](https://developer.mozilla.org/en-US/docs/Web/API/File) or an object which looks like this:

```js
{
  name: "some file name",
  type: "application/json"
  stream: <filestream, created by fs.createReadStream>
}
```

### CODE REVIEW

**Comment by achingbrain** [comment]
It would be more idiomatic if the API method returned a stream that we could `pipe` to.  E.g:

```javascript
const stream = fs.createReadStream('some file');

stream.pipe(api.documents.createFromStream({
  name: "some file name",
  type: "application/json"
})
```

This would also let the API user compose streaming chains, control high water marks, back pressure, etc.  See the [stream-handbook](https://github.com/substack/stream-handbook) for more.

**Comment by jimmythompson** [comment]
Agreed, that looks a lot nicer. I suppose the question is, would this be in addition to this change, or instead of it?

If we only offer createFromStream, we now have a method in the SDK which only works for the browser, and another which only works for Node.js. Is this something we're happy with?

**Comment by achingbrain** [comment]
We already have `create` and `createFromFile` so `createFromStream` didn't seem like a stretch 😉

I guess the choice really is to either overload the `createFromFile` method's options argument or to have different methods for different types.  I don't think it's a case of Node vs the browser because you can convert [Files into Node streams](https://www.npmjs.com/package/filereader-stream) in the browser and [Node streams into Files](https://www.npmjs.com/package/file-api) in Node if you really, really want to.

I can see the argument both ways - just `create` is a bit neater but explicit `createFromXXXX` methods make it more discoverable for people trying to actually use the API.

I tend to err on the side of ease of use so have a marginal preference for `createFromXXXX`.

**Comment by paulwib** [comment]
👍  to an explicit `createFromStream` method.

@jimmythompson can you make that change and I'll get a new release out.

**Comment by jimmythompson** [comment]
I took a look at it, and it looks like making this kind of interface would require a PR with Axios. They don't provide a streaming interface for uploading files, you just pass the stream into the `data` argument.

Before I go round making PRs, are there any constraints on what version of Axios we can use?

**Comment by achingbrain** [comment]
No, but if you could get them to release v1 that'd be grand.  I tried, and failed: mzabriskie/axios#432

**Comment by jimmythompson** [comment]
I split the methods, I haven't got the time at the moment to invest in opening a streaming interface into Axios I'm afraid.

Do we want to be aware of whether the user is in browser/node, and throw some errors? e.g. `This method is only available in a node environment, use createFromFile`

**Comment by achingbrain** [comment]
Looks good.

I get the feeling we should let Axios guard the input data type.  I can see the node transport adapter [emits sensible errors](https://github.com/mzabriskie/axios/blob/master/lib/adapters/http.js#L32-L42) but I think the browser version just [delegates to the underlying XHR request](https://github.com/mzabriskie/axios/blob/master/lib/adapters/xhr.js).

**Pull request closed without merging**
