### PR TITLE
WL-280 : added profiles/me endpoint

### PR DESCRIPTION
**Pull request by massa84**

### CODE REVIEW

**Comment by massa84** [comment]
Hi paul, can you please update the standalone build, increase the version number and create a new release ?

thank you very much.

**Comment by paulwib** [comment]
No problem, just released 0.5.0.

BTW thanks for this - was just about to add it myself so you saved me a job :)

**Comment by massa84** [comment]
I wasn't sure if implement all the profiles methods or just the one i needed.
If you want i can easily add all the other endpoints later today.

**Comment by paulwib** [comment]
Don't worry about it just yet, lets add them as we need them.

**Pull request merged**
