### PR TITLE
allow for sending FormData objects with new utility method

### PR DESCRIPTION
**Pull request by codename-**
New method is exactly same as the original `requestWithDataFun` apart it doesn't automatically convert data to JSON. This will allow for using `FormData` objects and create `multipart/form-data` requests.

### CODE REVIEW

**Comment by braxnu** [comment]
+1

**Comment by paulwib** [comment]
@codename- can you add comments to both function definitions explaining one explicitly converts to JSON and the other won't - would be good to mention how the latter behaves too. If you pass an object as data to axios does it convert to multipart/form-data by default?

**Comment by codename-** [comment]
@paulwib - after small research I've found this in **axios**: 

```javascript
function transformRequest(data, headers) {
  normalizeHeaderName(headers, 'Content-Type');
  if (utils.isFormData(data) ||
    utils.isArrayBuffer(data) ||
    utils.isStream(data) ||
    utils.isFile(data) ||
    utils.isBlob(data)
  ) {
    return data;
  }
  if (utils.isArrayBufferView(data)) {
    return data.buffer;
  }
  if (utils.isURLSearchParams(data)) {
    setContentTypeIfUnset(headers, 'application/x-www-form-urlencoded;charset=utf-8');
    return data.toString();
  }
  if (utils.isObject(data)) {
    setContentTypeIfUnset(headers, 'application/json;charset=utf-8');
    return JSON.stringify(data);
  }
  return data;
}
```

This is called within `dispatchRequest` in **axios** and it means that we could just use `requestWithDataFun` and omit `JSON.stringify` there – **axios** would do it for us.

I will update this PR accordingly to my findings.

**Comment by codename-** [comment]
rebased 👍

**Comment by achingbrain** [comment]
Since this has caused a major version bump, is there something that could be added to `UPGRADING.md` so people know what's changed?

**Comment by paulwib** [comment]
Sure, does [this change](https://github.com/Mendeley/mendeley-javascript-sdk/commit/5e8c695f049863bb6fb3b36d6b8820c9f4007adc) make sense?

**Comment by achingbrain** [comment]
Looks good.

**Comment by paulwib** [comment]
Cool, 7.01 released.

**Pull request merged**
