### PR TITLE
Fixing expired token not being refreshed correctly

### PR DESCRIPTION
**Pull request by massa84**

### CODE REVIEW

**Comment by customcommander** [comment]
Isn't the refresh already handled by the onFail function? https://github.com/Mendeley/mendeley-javascript-sdk/blob/master/lib/request.js#L87

If there's isn't a token or a valid token, I'm guessing that the `$.ajax` will fail and trigger the `onFail` function. Also that function takes into account the maximum number of attempts which I cannot see in your change? Any chance we might end up in a refreshToken loop?

**Comment by massa84** [comment]
read the comment. 
...
// because if you send 'Bearer ' you get a 400 rather than a 401 - is that a bug in the api?
...
if the token is 'invalid' then the refresh is correctly handled by the onFail.
But if you don't have any token ( token cookie expired for example) the ajax fails with the wrong responseCode (400 instead of 401), not triggering the refresh.
Actually if there isn't any token it's redirecting to the login without first trying to refresh and retrieve a new token.

**Comment by customcommander** [comment]
So if you don't have a token you should just authenticate then?

**Comment by massa84** [comment]
No. 
If you don't have an access token but the backend support the refresh token flow then you must first try to use the refresh token procedure and only if that fails redirect the user to the login page to re-authenticate.

**Comment by customcommander** [comment]
Alright :+1:

**Pull request merged**
